### PR TITLE
xbps-src: build depends of subpackages

### LINKED ISSUE #20508: xbps-src does not build depends of subpackages
This can lead to indexing package without its runtime dependencies being available (broken, misspelled, not yet build).
So depends of subpackages should be build, same as depends of main package.

On the other hand, building them can introduce cycles.

### PR DESCRIPTION
**Pull request by Chocimier**
resolves #20508

### CODE REVIEW

File: common/xbps-src/shutils/build_dependencies.sh [hunk 1]
```diff
@@ -1,13 +1,21 @@
...
 setup_pkg_depends() {
-    local pkg="$1" out="$2" j _rpkgname _depname _pkgname foo _deps
+    local pkg="$1" out="$2" with_subpkgs="$3" j _rpkgname _depname _pkgname foo _deps collected
 
     if [[ $pkg ]]; then
         # subpkg
         if declare -f ${pkg}_package >/dev/null; then
             ${pkg}_package
         fi
+    elif [[ $with_subpkgs ]]; then
```
Comment (xtraeme) [inline common/xbps-src/shutils/build_dependencies.sh:11]: hmm now that I'm looking at this more carefully, this won't work because `$pkg` is always true, so this branch will be skipped due to `elif`.

File: common/xbps-src/shutils/build_dependencies.sh [hunk 2]
```diff
@@ -296,9 +304,9 @@ install_pkg_deps() {
     #
     # Target run time dependencies
     #
-    if [[ ${depends} ]]; then
+    local _cleandeps=$(setup_pkg_depends "" 1 1) || exit 1
```
Comment (xtraeme) [inline common/xbps-src/shutils/build_dependencies.sh:307]: because `$1` is set in `setup_pkg_depends` the 3rd argument will be skipped.
That means that here 2nd argument should be unset to make this work as expected.

File: common/xbps-src/shutils/show.sh [hunk 3]
```diff
@@ -89,7 +89,7 @@ show_pkg_build_depends() {
 }
 
 show_pkg_build_deps() {
-    show_pkg_build_depends "${hostmakedepends} ${makedepends} $(setup_pkg_depends '' 1)"
+    show_pkg_build_depends "${hostmakedepends} ${makedepends} $(setup_pkg_depends '' 1 1)"
```
Comment (xtraeme) [inline common/xbps-src/shutils/show.sh:92]: ditto, 2nd argument here should be unset to make this work.

Comment (xtraeme) [reply common/xbps-src/shutils/show.sh:92]: Change this to `$(setup_pkg_depends '' '' 1)`

File: common/xbps-src/shutils/build_dependencies.sh (hunk 2 above)
Comment (xtraeme) [reply common/xbps-src/shutils/build_dependencies.sh:307]: Change this to `$(setup_pkg_depends '' '' 1)`

Comment (xtraeme) [reply common/xbps-src/shutils/build_dependencies.sh:307]: oh doh! I confused the args. It's ok in fact!

**Comment by xtraeme** [comment]
It's ok! I confused the arg order between funcs in my previous review. Thanks!
